github-actions:
  - changed-files:
    - any-glob-to-any-file: 
      - ".github/**/*"
docker:
  - changed-files:
    - any-glob-to-any-file: 
      - "Dockerfile"
      - "docker-compose.yaml"
app:
  - all:
    - changed-files:
      - any-glob-to-any-file: 
        - 'common/**'
        - 'internal/**'
        - 'config.ini'
        - 'requirements.txt'
        - 'main.py'
