version: '3.8'

services:
  redis:
    image: redis:latest@sha256:5c7c0445ed86918cb9efb96d95a6bfc03ed2059fe2c5f02b4d74f477ffe47915
    container_name: redis
    ports:
      - "6379:6379"
  unixbot:
    image: unixbot
    ports:
      - "8000:8000"
    container_name: unixbot
    volumes:
      - ./config.ini:/app/config.ini
    depends_on:
      - redis