version: '3.8'

services:
  redis:
    image: redis:latest@sha256:832d7785830f3f4b559300e6191fc914b15642c1935252338825cf4332200148
    container_name: redis
    ports:
      - "6379:6379"
  unixbot:
    image: unixbot
    ports:
      - "8000:8000"
    container_name: unixbot
    volumes:
      - ./config.ini:/app/config.ini
    depends_on:
      - redis