version: '3.8'

services:
  redis:
    image: redis:latest@sha256:2c2dff791878316e3b083188be0d578423b24813cdda5de0e80ea4f7b3e6bfd6
    container_name: redis
    ports:
      - "6379:6379"
  unixbot:
    image: unixbot
    ports:
      - "8000:8000"
    container_name: unixbot
    volumes:
      - ./config.ini:/app/config.ini
    depends_on:
      - redis